services:
  mongodb:
      image: mongo:7.0
      container_name: saam-mongodb
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      ports:
        - "${MONGO_PORT:-27018}:27018"
      healthcheck:
        test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 40s

  backend-saam:
    image: saam-backend:latest
    container_name: saam-backend
    restart: always
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      APP_DATABASE_URI: ${APP_DATABASE_URI}
      MAILTRAP_HOST: ${MAILTRAP_HOST}
      MAILTRAP_TOKEN: ${MAILTRAP_TOKEN}
      MAILTRAP_SENDER_NAME: ${MAILTRAP_SENDER_NAME}
      MAILTRAP_SENDER_EMAIL: ${MAILTRAP_SENDER_EMAIL}
      DAYJS_START: ${DAYJS_START}
      ACADEMIC_YEAR: ${ACADEMIC_YEAR}
      ACADEMIC_TERM: ${ACADEMIC_TERM}