services:
  backend-saam:
    image: saam-backend:latest
    container_name: saam-backend
    restart: always
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      APP_DATABASE_URI: ${APP_DATABASE_URI}
      MAILTRAP_HOST: ${MAILTRAP_HOST}
      MAILTRAP_TOKEN: ${MAILTRAP_TOKEN}
      MAILTRAP_SENDER_NAME: ${MAILTRAP_SENDER_NAME}
      MAILTRAP_SENDER_EMAIL: ${MAILTRAP_SENDER_EMAIL}
      DAYJS_START: ${DAYJS_START}
      ACADEMIC_YEAR: ${ACADEMIC_YEAR}
      ACADEMIC_TERM: ${ACADEMIC_TERM}